export var url:string = 'https://4bfa83f8.ngrok.io';

export var empresasLogos = {
    'ACERIAS DE COLOMBIA S.A.S': 'Acesco',
    'ACERIAS PAZ DEL RIO S.A.': 'Pazdelrio',
    'ALPINA PRODUCTOS ALIMENTICIOS S.A.': 'Alpina',
    'AMCOR RIGID PLASTICS DE COLOMBIA S.A.': 'Amcor',
    'BAVARIA S.A.': 'Bavaria',
    'BAYER CROPSCIENCE S.A.': 'Bayer',
    'C.I. PRODECO S.A.': 'Prodeco',
    'CABLES DE ENERGIA Y TELECOMUNICACIONES S.A.': 'Centelsa',
    'CARVAJAL PULPA Y PAPEL S.A.': 'Carvajal',
    'CEMENTOS ARGOS S.A.': 'Argos',
    'CEMENTOS TEQUENDAMA S.A.': 'Tequendama',
    'CEMENTOS TEQUENDAMA': 'Tequendama',
    'CEMEX COLOMBIA S.A.': 'Cemex',
    'CERVECERIA UNION S.A.': 'Union',
    'CHALLENGER S.A.S.': 'Challenger',
    'CIA. DE GALLETAS NOEL S.A.': 'Noel',
    'COCACOLA FEMSA': 'Femsa',
    'COLOMBINA S.A.': 'Colombina',
    'CONTECAR': 'Contecar',
    'DRINKS DE COLOMBIA S.A.S': 'Drinks',
    'ECOPETROL S.A.': 'Ecopetrol',
    'FABRICATO S.A.': 'Fabricato',
    'FLEXO SPRING': 'Flexospring',
    'GRUPO PHOENIX': 'Phoenix',
    'HOCOL S.A.': 'Hocol',
    'HOLCIM COLOMBIA S.A.': 'Holcim',
    'INGENIO CARMELITA S.A.': 'Carmelita',
    'INGENIO LA CABAÑA S.A.': 'Cabaña',
    'INGENIO PROVIDENCIA S.A.': 'Providencia',
    'INGENIO RISARALDA': 'Risaralda',
    'INGENIO RISARALDA S.A.': 'Risaralda',
    'INGENIO SAN CARLOS': 'Sancarlos',
    'KAESER': 'Kaeser',
    'KAESER COMPRESORES DE COLOMBIA LTDA.': 'Kaeser',
    'LEONISA S.A.': 'Leonisa',
    'LINDE COLOMBIA S.A.': 'Linde',
    'MEALS DE COLOMBIA S.A.S.': 'Meals',
    'MULTIDIMENSIONALES S.A.': 'Phoenix',
    'NACIONAL DE CHOCOLATES S.A.': 'Chocolates',
    'NESTLÉ PURINA PETCARE DE COLOMBIA S.A.': 'Purina',
    'OLEODUCTO DE LOS LLANOS ORIENTALES S.A.': 'ODL',
    'PAVCO': 'Pavco',
    'PCH SUBA': 'Acueducto',
    'PCH USAQUEN': 'Acueducto',
    'PGI COLOMBIA LTDA': 'PGI',
    'POSTOBON S.A.': 'Postobon',
    'PRODUCTOS ALIMENTICIOS DORIA S.A.S.': 'Doria',
    'PRODUCTOS FAMILIA S.A.': 'Familia',
    'PROPILCO S.A.': 'Propilco',
    'PUERTO BRISA S.A.': 'Brisa',
    'QUALA S.A.': 'Quala',
    'RED EAGLE': 'Redeagle',
    'SMURFIT KAPPA CARTON DE COLOMBIA S.A': 'Smurfit',
    'SOCIEDAD PORTUARIA REGIONAL DE BUENAVENTURA S.A.': 'Sprb',
    'SOCIEDAD PORTUARIA REGIONAL DE CARTAGENA S.A': 'Cartagena',
    'SOFASA S.A.': 'Sofasa',
    'TABLEMAC': 'Tablemac',
    'TERMINAL DE CONTENEDORES DE CARTAGENA S.A': 'Contecar',
    'T.C.BUEN S.A.': 'Tcbuen',    
    
    
    
} 
