export var url:string = 'https://48a37561.ngrok.io';

export var empresasLogos = {
    'ACERIAS DE COLOMBIA S.A.S': 'Acesco',
    'ACERIAS PAZ DEL RIO S.A.': 'Pazdelrio',
    'ALPINA PRODUCTOS ALIMENTICIOS S.A.': 'Alpina',
    'AMCOR RIGID PLASTICS DE COLOMBIA S.A.': 'Amcor',
    'BAVARIA S.A.': 'Bavaria',
    'BAYER CROPSCIENCE S.A.': 'Bayer',
    'C.I. PRODECO S.A.': 'Prodeco',
    'CABLES DE ENERGIA Y TELECOMUNICACIONES S.A.': 'Centelsa',
    'CARVAJAL PULPA Y PAPEL S.A.': 'Carvajal',
    'CEMENTOS ARGOS S.A.': 'Argos',
    'CEMENTOS TEQUENDAMA S.A.': 'Tequendama',
    'CEMENTOS TEQUENDAMA': 'Tequendama',
    'CEMEX COLOMBIA S.A.': 'Cemex',
    'CERVECERIA UNION S.A.': 'Union',
    'CHALLENGER S.A.S.': 'Challenger',
    'CIA. DE GALLETAS NOEL S.A.': 'Noel',
    'COCACOLA FEMSA': 'Femsa',
    'COLOMBINA S.A.': 'Colombina',
    'CONTECAR': 'Contecar',
    'DRINKS DE COLOMBIA S.A.S': 'Drinks',
    'ECOPETROL S.A.': 'Ecopetrol',
    'FABRICATO S.A.': 'Fabricato',
    'FLEXO SPRING': 'Flexospring',
    'GRUPO PHOENIX': 'Phoenix',
    'HOCOL S.A.': 'Hocol',
    'HOLCIM COLOMBIA S.A.': 'Holcim',
    'T.C.BUEN S.A.': 'Tcbuen',
    'PAVCO': 'Pavco',
    'PRODUCTOS FAMILIA S.A.': 'Familia',
    'POSTOBON S.A.': 'Postobon',
    'SOCIEDAD PORTUARIA REGIONAL DE BUENAVENTURA S.A.': 'Sprb'
} 
